#ifndef MINDGROVE_PINCTRL_DT_BINDINGS_H
#define MINDGROVE_PINCTRL_DT_BINDINGS_H

#define MINDGROVE_PINMUX(mux_idx, bit_val) \
    (((mux_idx) & 0x1F) | (((bit_val) & 0x1) << 8))

#define MG_GPIO0      MINDGROVE_PINMUX(0,  0)
#define MG_GPIO1      MINDGROVE_PINMUX(1,  0)
#define MG_GPIO2      MINDGROVE_PINMUX(2,  0)
#define MG_GPIO3      MINDGROVE_PINMUX(3,  0)
#define MG_GPIO4      MINDGROVE_PINMUX(4,  0)
#define MG_GPIO5      MINDGROVE_PINMUX(5,  0)
#define MG_GPIO6      MINDGROVE_PINMUX(6,  0)
#define MG_GPIO7      MINDGROVE_PINMUX(7,  0)

#define MG_PWM0       MINDGROVE_PINMUX(0,  1)
#define MG_PWM1       MINDGROVE_PINMUX(1,  1)
#define MG_PWM2       MINDGROVE_PINMUX(2,  1)
#define MG_PWM3       MINDGROVE_PINMUX(3,  1)
#define MG_PWM4       MINDGROVE_PINMUX(4,  1)
#define MG_PWM5       MINDGROVE_PINMUX(5,  1)
#define MG_PWM6       MINDGROVE_PINMUX(6,  1)
#define MG_PWM7       MINDGROVE_PINMUX(7,  1)

#define MG_GPIO17     MINDGROVE_PINMUX(8,  0)
#define MG_GPIO18     MINDGROVE_PINMUX(9,  0)
#define MG_GPIO19     MINDGROVE_PINMUX(10, 0)
#define MG_GPIO20     MINDGROVE_PINMUX(11, 0)
#define MG_GPIO21     MINDGROVE_PINMUX(12, 0)
#define MG_GPIO22     MINDGROVE_PINMUX(13, 0)

#define MG_PWM8       MINDGROVE_PINMUX(8,  1)
#define MG_PWM9       MINDGROVE_PINMUX(9,  1)
#define MG_PWM10      MINDGROVE_PINMUX(10, 1)
#define MG_PWM11      MINDGROVE_PINMUX(11, 1)
#define MG_PWM12      MINDGROVE_PINMUX(12, 1)
#define MG_PWM13      MINDGROVE_PINMUX(13, 1)

#define MG_SPI2_MOSI  MINDGROVE_PINMUX(14, 0)
#define MG_SPI2_MISO  MINDGROVE_PINMUX(15, 0)
#define MG_SPI2_NCS   MINDGROVE_PINMUX(16, 0)

#define MG_GPIO32     MINDGROVE_PINMUX(14, 1)
#define MG_GPIO33     MINDGROVE_PINMUX(15, 1)
#define MG_GPIO34     MINDGROVE_PINMUX(16, 1)

#define MG_SPI3_MOSI  MINDGROVE_PINMUX(17, 0)
#define MG_SPI3_MISO  MINDGROVE_PINMUX(18, 0)
#define MG_SPI3_NCS   MINDGROVE_PINMUX(19, 0)

#define MG_GPIO35     MINDGROVE_PINMUX(17, 1)
#define MG_GPIO36     MINDGROVE_PINMUX(18, 1)
#define MG_GPIO37     MINDGROVE_PINMUX(19, 1)

#define MG_GPIO8      MINDGROVE_PINMUX(20, 0)
#define MG_GPIO9      MINDGROVE_PINMUX(21, 0)

#define MG_UART3_TX   MINDGROVE_PINMUX(20, 1)
#define MG_UART3_RX   MINDGROVE_PINMUX(21, 1)

#define MG_GPIO11     MINDGROVE_PINMUX(22, 0)
#define MG_GPIO15     MINDGROVE_PINMUX(23, 0)

#define MG_UART4_TX   MINDGROVE_PINMUX(22, 1)
#define MG_UART4_RX   MINDGROVE_PINMUX(23, 1)

#define MG_GPTIMER0   MINDGROVE_PINMUX(24, 0)
#define MG_GPTIMER1   MINDGROVE_PINMUX(25, 0)
#define MG_GPTIMER2   MINDGROVE_PINMUX(26, 0)
#define MG_GPTIMER3   MINDGROVE_PINMUX(27, 0)

#define MG_GPIO38     MINDGROVE_PINMUX(24, 1)
#define MG_GPIO39     MINDGROVE_PINMUX(25, 1)
#define MG_GPIO40     MINDGROVE_PINMUX(26, 1)
#define MG_GPIO41     MINDGROVE_PINMUX(27, 1)

#define MG_JTAG_TDI   MINDGROVE_PINMUX(28, 0)
#define MG_JTAG_TMS   MINDGROVE_PINMUX(29, 0)
#define MG_JTAG_TDO   MINDGROVE_PINMUX(30, 0)

#define MG_GPIO42     MINDGROVE_PINMUX(28, 1)
#define MG_GPIO43     MINDGROVE_PINMUX(29, 1)
#define MG_GPIO44     MINDGROVE_PINMUX(30, 1)

#endif /* MINDGROVE_PINCTRL_DT_BINDINGS_H */