#ifndef SOC_RISCV_MINDGROVE_SOC_OFFSETS_H_
#define SOC_RISCV_MINDGROVE_SOC_OFFSETS_H_

#ifdef CONFIG_RISCV_SOC_OFFSETS

	#define GEN_SOC_OFFSET_SYMS()

#endif  /* CONFIG_RISCV_SOC_OFFSETS */

#endif  /* SOC_RISCV_MINDGROVE_SOC_OFFSETS_H_*/
