# Enable prontf

CONFIG_UART_MINDGROVE=y
CONFIG_UART_CONSOLE=y
CONFIG_MULTITHREADING=y
CONFIG_PRINTK=y
# Enable FLASH driver
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=n
CONFIG_FLASH_LOG_LEVEL_DBG=y

CONFIG_FLASH_MINDGROVE=y
CONFIG_FLASH_JESD216_API=y
