CONFIG_MULTITHREADING=y
CONFIG_UART_MINDGROVE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_EARLY_CONSOLE=y
CONFIG_GPIO=y
# CONFIG_RISCV_HAS_PLIC=y 
CONFIG_GEN_ISR_TABLES=y
CONFIG_GEN_SW_ISR_TABLE=y
CONFIG_GEN_IRQ_VECTOR_TABLE=y
CONFIG_INTC_SINGLE_AGGREGATOR=y
CONFIG_NUM_IRQS=16 
CONFIG_MAX_IRQ_PER_AGGREGATOR=64 
CONFIG_PLIC_MEIP_PRIORITY=1
# CONFIG_2ND_LEVEL_INTERRUPTS=y
CONFIG_INTC_INIT_PRIORITY=40
CONFIG_GEN_SW_ISR_TABLE=y
CONFIG_GEN_ISR_TABLES=y
# CONFIG_SW_ISR_TABLE=y
CONFIG_DYNAMIC_INTERRUPTS=y
# CONFIG_RISCV_PLIC=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_GEN_IRQ_VECTOR_TABLE=y
CONFIG_NUM_2ND_LEVEL_AGGREGATORS=1
CONFIG_MULTI_LEVEL_INTERRUPTS=y
CONFIG_2ND_LEVEL_INTERRUPTS=y
CONFIG_NUM_2ND_LEVEL_AGGREGATORS=1
CONFIG_2ND_LVL_INTR_00_OFFSET=11
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_GPIO_MINDGROVE_AUTO_IRQ_CONNECT=n
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_2ND_LVL_INTR_00_OFFSET_START=32
# Enables generic multi-level interrupt support logic
# CONFIG_ARCH_INTERRUPT_VECTOR_AGGREGATOR=y
CONFIG_PLIC=y
CONFIG_RISCV_VECTORED_MODE=y
CONFIG_IRQ_VECTOR_TABLE_JUMP_BY_CODE=y




