# CONFIG_CODE_DATA_RELOCATION=n
# CONFIG_HAVE_CUSTOM_LINKER_SCRIPT=y
# CONFIG_CUSTOM_LINKER_SCRIPT="linker_secure-iot.ld"
# CONFIG_XIP=n
# # CONFIG_FLASH=y
# CONFIG_FLASH_BASE_ADDRESS=0x90000000
# CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_MINDGROVE=y
# CONFIG_PLIC=n
# CONFIG_MINDGROVE_PLIC=y
# CONFIG_PLIC_MEIP_PRIORITY=3
CONFIG_UART_CONSOLE=y
CONFIG_MULTITHREADING=y
CONFIG_PRINTK=y
