# Basic OS Features
CONFIG_MULTITHREADING=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y

# Hardware Support
CONFIG_PLIC=y
CONFIG_DMA=y
CONFIG_DMA_MINDGROVE=y
#CONFIG_RISCV_PLIC=y

CONFIG_MULTI_LEVEL_INTERRUPTS=y
CONFIG_2ND_LEVEL_INTERRUPTS=y
CONFIG_NUM_2ND_LEVEL_AGGREGATORS=1
CONFIG_2ND_LVL_INTR_00_OFFSET=11

# This symbol is often the one gen_isr_tables.py looks for 
# # to define the size of the 2nd level table for RISC-V.
CONFIG_MAX_IRQ_PER_AGGREGATOR=81

# # Ensure the total pool is large enough
# CONFIG_NUM_IRQS=120

# Note: Removed manual ISR_TBL_OFFSET as it's not a user-definable 
# Kconfig symbol for this specific RISC-V arch.