cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(aes_tests)

target_sources(app PRIVATE src/main.c)

# CBC
if(CONFIG_AES_TEST_CBC_GFSBOX)
    target_sources(app PRIVATE src/test_aes_cbc_gfsbox.c)
endif()
if(CONFIG_AES_TEST_CBC_KEYSBOX)
    target_sources(app PRIVATE src/test_aes_cbc_keysbox.c)
endif()
if(CONFIG_AES_TEST_CBC_MMT)
    target_sources(app PRIVATE src/test_aes_cbc_mmt.c)
endif()
if(CONFIG_AES_TEST_CBC_VARKEY_128)
    target_sources(app PRIVATE src/test_aes_cbc_varkey_128.c)
endif()
if(CONFIG_AES_TEST_CBC_VARKEY_192)
    target_sources(app PRIVATE src/test_aes_cbc_varkey_192.c)
endif()
if(CONFIG_AES_TEST_CBC_VARKEY_256)
    target_sources(app PRIVATE src/test_aes_cbc_varkey_256.c)
endif()
if(CONFIG_AES_TEST_CBC_VARTXT_128)
    target_sources(app PRIVATE src/test_aes_cbc_vartxt_128.c)
endif()
if(CONFIG_AES_TEST_CBC_VARTXT_192)
    target_sources(app PRIVATE src/test_aes_cbc_vartxt_192.c)
endif()
if(CONFIG_AES_TEST_CBC_VARTXT_256)
    target_sources(app PRIVATE src/test_aes_cbc_vartxt_256.c)
endif()
if(CONFIG_AES_TEST_CBC_MCT)
    target_sources(app PRIVATE src/test_aes_cbc_mct.c)
endif()