cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(aes_cbc_tests)

target_sources(app PRIVATE src/main.c)

if(CONFIG_AES_CBC_GFSBOX)
    target_sources(app PRIVATE src/test_aes_cbc_gfsbox.c)
endif()
if(CONFIG_AES_CBC_KEYSBOX_128 OR CONFIG_AES_CBC_KEYSBOX_192 OR CONFIG_AES_CBC_KEYSBOX_256)
    target_sources(app PRIVATE src/test_aes_cbc_keysbox.c)
endif()
if(CONFIG_AES_CBC_MMT)
    target_sources(app PRIVATE src/test_aes_cbc_mmt.c)
endif()

if(CONFIG_AES_CBC_MCT)
    target_sources(app PRIVATE src/test_aes_cbc_mct.c)
endif()

# VARKEY
if(CONFIG_AES_CBC_VARKEY_128_01 OR CONFIG_AES_CBC_VARKEY_128_02 OR
   CONFIG_AES_CBC_VARKEY_128_03 OR CONFIG_AES_CBC_VARKEY_128_04 OR
   CONFIG_AES_CBC_VARKEY_128_05 OR CONFIG_AES_CBC_VARKEY_128_06)
    target_sources(app PRIVATE src/test_aes_cbc_varkey_128.c)
endif()

if(CONFIG_AES_CBC_VARKEY_192_01 OR CONFIG_AES_CBC_VARKEY_192_02 OR
   CONFIG_AES_CBC_VARKEY_192_03 OR CONFIG_AES_CBC_VARKEY_192_04 OR
   CONFIG_AES_CBC_VARKEY_192_05 OR CONFIG_AES_CBC_VARKEY_192_06 OR
   CONFIG_AES_CBC_VARKEY_192_07 OR CONFIG_AES_CBC_VARKEY_192_08)
    target_sources(app PRIVATE src/test_aes_cbc_varkey_192.c)
endif()

if(CONFIG_AES_CBC_VARKEY_256_01 OR CONFIG_AES_CBC_VARKEY_256_02 OR
   CONFIG_AES_CBC_VARKEY_256_03 OR CONFIG_AES_CBC_VARKEY_256_04 OR
   CONFIG_AES_CBC_VARKEY_256_05 OR CONFIG_AES_CBC_VARKEY_256_06 OR
   CONFIG_AES_CBC_VARKEY_256_07 OR CONFIG_AES_CBC_VARKEY_256_08 OR
   CONFIG_AES_CBC_VARKEY_256_09 OR CONFIG_AES_CBC_VARKEY_256_10 OR
   CONFIG_AES_CBC_VARKEY_256_11)
    target_sources(app PRIVATE src/test_aes_cbc_varkey_256.c)
endif()

# VARTXT 128
if(CONFIG_AES_CBC_VARTXT_128_01 OR CONFIG_AES_CBC_VARTXT_128_02 OR
   CONFIG_AES_CBC_VARTXT_128_03 OR CONFIG_AES_CBC_VARTXT_128_04 OR
   CONFIG_AES_CBC_VARTXT_128_05 OR CONFIG_AES_CBC_VARTXT_128_06)
    target_sources(app PRIVATE src/test_aes_cbc_vartxt_128.c)
endif()

if(CONFIG_AES_CBC_VARTXT_192_01 OR CONFIG_AES_CBC_VARTXT_192_02 OR
   CONFIG_AES_CBC_VARTXT_192_03 OR CONFIG_AES_CBC_VARTXT_192_04 OR
   CONFIG_AES_CBC_VARTXT_192_05 OR CONFIG_AES_CBC_VARTXT_192_06)
    target_sources(app PRIVATE src/test_aes_cbc_vartxt_192.c)
endif()

if(CONFIG_AES_CBC_VARTXT_256_01 OR CONFIG_AES_CBC_VARTXT_256_02 OR
   CONFIG_AES_CBC_VARTXT_256_03 OR CONFIG_AES_CBC_VARTXT_256_04 OR
   CONFIG_AES_CBC_VARTXT_256_05 OR CONFIG_AES_CBC_VARTXT_256_06)
    target_sources(app PRIVATE src/test_aes_cbc_vartxt_256.c)
endif()