# ---------------- Kernel ----------------
CONFIG_MULTITHREADING=n
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_IDLE_STACK_SIZE=256

# # ---------------- Crypto ----------------
CONFIG_CRYPTO=y
CONFIG_CRYPTO_MINDGROVE_AES=y


CONFIG_AES_CBC_GFSBOX=n
CONFIG_AES_CBC_KEYSBOX_128=y
CONFIG_AES_CBC_KEYSBOX_192=n
CONFIG_AES_CBC_KEYSBOX_256=n
CONFIG_AES_CBC_MMT=n

# AES CBC VARTXT 128 (01-06)
CONFIG_AES_CBC_VARKEY_128_01=n
CONFIG_AES_CBC_VARKEY_128_02=n
CONFIG_AES_CBC_VARKEY_128_03=n
CONFIG_AES_CBC_VARKEY_128_04=n
CONFIG_AES_CBC_VARKEY_128_05=n
CONFIG_AES_CBC_VARKEY_128_06=n

# AES CBC VARTXT 192 (01-08)
CONFIG_AES_CBC_VARKEY_192_01=n
CONFIG_AES_CBC_VARKEY_192_02=n
CONFIG_AES_CBC_VARKEY_192_03=n
CONFIG_AES_CBC_VARKEY_192_04=n
CONFIG_AES_CBC_VARKEY_192_05=n
CONFIG_AES_CBC_VARKEY_192_06=n
CONFIG_AES_CBC_VARKEY_192_07=n
CONFIG_AES_CBC_VARKEY_192_08=n

# AES CBC VARTXT 256 (01-11)
CONFIG_AES_CBC_VARKEY_256_01=n
CONFIG_AES_CBC_VARKEY_256_02=n
CONFIG_AES_CBC_VARKEY_256_03=n
CONFIG_AES_CBC_VARKEY_256_04=n
CONFIG_AES_CBC_VARKEY_256_05=n
CONFIG_AES_CBC_VARKEY_256_06=n
CONFIG_AES_CBC_VARKEY_256_07=n
CONFIG_AES_CBC_VARKEY_256_08=n
CONFIG_AES_CBC_VARKEY_256_09=n
CONFIG_AES_CBC_VARKEY_256_10=n
CONFIG_AES_CBC_VARKEY_256_11=n

# AES CBC VARTXT 128 (01-06)
CONFIG_AES_CBC_VARTXT_128_01=n
CONFIG_AES_CBC_VARTXT_128_02=n
CONFIG_AES_CBC_VARTXT_128_03=n
CONFIG_AES_CBC_VARTXT_128_04=n
CONFIG_AES_CBC_VARTXT_128_05=n
CONFIG_AES_CBC_VARTXT_128_06=n

# AES CBC VARTXT 192 (01-06)
CONFIG_AES_CBC_VARTXT_192_01=n
CONFIG_AES_CBC_VARTXT_192_02=n
CONFIG_AES_CBC_VARTXT_192_03=n
CONFIG_AES_CBC_VARTXT_192_04=n
CONFIG_AES_CBC_VARTXT_192_05=n
CONFIG_AES_CBC_VARTXT_192_06=n

# AES CBC VARTXT 256 (01-06)
CONFIG_AES_CBC_VARTXT_256_01=n
CONFIG_AES_CBC_VARTXT_256_02=n
CONFIG_AES_CBC_VARTXT_256_03=n
CONFIG_AES_CBC_VARTXT_256_04=n
CONFIG_AES_CBC_VARTXT_256_05=n
CONFIG_AES_CBC_VARTXT_256_06=n
# ---------------- UART / printk ---------
CONFIG_SERIAL=y
CONFIG_UART_MINDGROVE=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

# ---------------- Memory ----------------
CONFIG_HEAP_MEM_POOL_SIZE=0

# ---------------- Disable bloat ---------
CONFIG_LOG=n
CONFIG_ASSERT=n
CONFIG_DEBUG=n
CONFIG_POSIX_API=n
CONFIG_TIMING_FUNCTIONS=n
CONFIG_HEAP_MEM_POOL_SIZE=2048

# # ---------------- Libc ------------------
# CONFIG_MINIMAL_LIBC=y
# CONFIG_NEWLIB_LIBC=n
CONFIG_MINIMAL_LIBC_RAND=y

# ---------------- Size ------------------
CONFIG_SIZE_OPTIMIZATIONS=y